import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "../components/HeaderComponents/header";
import Footer from "../components/HeaderComponents/footer";
import HeaderDetails from "@/components/HeaderComponents/headerDetails";
import '../styles/main.scss'; // Adjust the path based on your actual file structure
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nexcel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
       
         <HeaderDetails />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
